name: minoshop
description: An exetremly famous shop ever

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  google_fonts: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  dio: ^4.0.0
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/on_boarding/
    -  assets/default/
    -  assets/user/
